[package]
name = "drive_ai"
version = "0.1.0"
cairo-version = "2.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" }
cubit = {git = "https://github.com/tarrencev/cubit" }
# TODO: remove `branch` key when "prepare-release" is merged on Orion's `main` branch.
orion = { git = "https://github.com/gizatechxyz/orion"}

[[target.dojo]]

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

# Default account for katana with seed = 0
account_address = "0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x0300001800000000300000180000000000030000000000003006001800006600"
